package projetocg.V;

import java.awt.BorderLayout;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import projetocg.C.ArquivoController;
import projetocg.C.TransformacaoController;
import projetocg.M.Ponto;

/**
 *
 * @author Evelyn
 */
public class Tela extends javax.swing.JFrame {
    
    private ArquivoController arqController;
    private TransformacaoController transfController = new TransformacaoController();
    private ArrayList<Ponto> pontosIniciais = new ArrayList<>();
    private ArrayList<Ponto> pontosAtuais = new ArrayList<>();
    private JFrame f;
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLocal = new javax.swing.JTextField();
        BotaoIR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        translacao = new javax.swing.JRadioButton();
        escala = new javax.swing.JRadioButton();
        rotacao = new javax.swing.JRadioButton();
        jTextFieldPontosIniciais = new javax.swing.JTextField();
        jTextFieldPontosAtuais = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Diretório:");

        jTextFieldLocal.setEditable(false);

        BotaoIR.setText("Buscar");
        BotaoIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoIRActionPerformed(evt);
            }
        });

        jLabel2.setText("Transformação:");

        translacao.setText("Translação");
        translacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translacaoActionPerformed(evt);
            }
        });

        escala.setText("Escala");
        escala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalaActionPerformed(evt);
            }
        });

        rotacao.setText("Rotação");
        rotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotacaoActionPerformed(evt);
            }
        });

        jTextFieldPontosIniciais.setEditable(false);

        jTextFieldPontosAtuais.setEditable(false);

        jLabel9.setText("Coord Anterior:");

        jLabel10.setText("Coord Atual:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(44, 44, 44)
                                .addComponent(jTextFieldLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotaoIR))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(translacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(escala)
                                .addGap(18, 18, 18)
                                .addComponent(rotacao)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldPontosIniciais, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldPontosAtuais, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoIR))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(translacao)
                    .addComponent(escala)
                    .addComponent(rotacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldPontosIniciais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldPontosAtuais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotacaoActionPerformed
        translacao.setSelected(false);
        escala.setSelected(false);
        pontosAtuais = transfController.rotacaoController(pontosIniciais);
        desenha(pontosAtuais);
        mostraCoordenadas();
        pontosIniciais = pontosAtuais;
    }//GEN-LAST:event_rotacaoActionPerformed

    private void escalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalaActionPerformed
        translacao.setSelected(false);
        rotacao.setSelected(false);
        pontosAtuais = transfController.escalaController(pontosIniciais);
        desenha(pontosAtuais);
        mostraCoordenadas();
        pontosIniciais = pontosAtuais;
    }//GEN-LAST:event_escalaActionPerformed

    private void translacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translacaoActionPerformed
        escala.setSelected(false);
        rotacao.setSelected(false);
        pontosAtuais = transfController.translacaoController(pontosIniciais);
        desenha(pontosAtuais);
        mostraCoordenadas();
        pontosIniciais = pontosAtuais;
    }//GEN-LAST:event_translacaoActionPerformed

    public void mostraCoordenadas(){
        jTextFieldPontosIniciais.setText(preencheTxtComPontos(pontosIniciais));
        jTextFieldPontosAtuais.setText(preencheTxtComPontos(pontosAtuais));
    }
        
    public String preencheTxtComPontos(ArrayList<Ponto> pontos){
        String pts = "";
        for(int i=0; i<pontos.size(); i++){
            pts +=" | X: "+pontos.get(i).getX() + " Y: "+ pontos.get(i).getY();
        }
        return pts;
    }
    
    public void desenha(ArrayList<Ponto> pontos){
        f = new BresenhamPanel();
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setVisible(true);
        f.add(new Bresenham(pontos, pontos.size()), BorderLayout.CENTER);
        f.setTitle("Polígono");
        f.setResizable(true);
        f.pack();
        f.setLocationRelativeTo(null);
    }

    
    private void BotaoIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoIRActionPerformed
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i = file.showSaveDialog(null);
        if (i == 1) { //se for clicado em cancelar
            jTextFieldLocal.setText("");
        } else { //se for clicado em salvar
            File arquivo = file.getSelectedFile();
            jTextFieldLocal.setText(arquivo.getPath());
            String caminho = jTextFieldLocal.getText();
            arqController = new ArquivoController(caminho);
            pontosIniciais = arqController.getPontos();
            desenha(pontosIniciais);
            jTextFieldPontosIniciais.setText(preencheTxtComPontos(pontosIniciais));
            jTextFieldPontosAtuais.setText(preencheTxtComPontos(pontosAtuais));
        }
    }//GEN-LAST:event_BotaoIRActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame tela;
                tela = new Tela();
                tela.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoIR;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton escala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextFieldLocal;
    private javax.swing.JTextField jTextFieldPontosAtuais;
    private javax.swing.JTextField jTextFieldPontosIniciais;
    private javax.swing.JRadioButton rotacao;
    private javax.swing.JRadioButton translacao;
    // End of variables declaration//GEN-END:variables
}
